import { ThemeProvider } from '../context/ThemeContext'
import NavBar from '../component/navbar/NavBar'
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App 2',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <NavBar/>
          <div className='container'>
          {children}
          </div>
        </ThemeProvider>
        </body>
    </html>
  )
}
